#!/usr/bin/env node
/**
 * The single zero-drift generation pipeline (CLAUDE.md §9). Run as `pnpm gen:api` from the root.
 *
 *   1. FastAPI (Pydantic schemas) → packages/shared-schema/openapi.json
 *   2. openapi-typescript          → packages/shared-schema/types.ts
 *   3. typed openapi-fetch client  → packages/web/src/lib/api-client.ts
 *   4. TanStack Query hooks        → packages/web/src/generated/hooks.ts
 *
 * Every output is committed; CI fails on any diff. Determinism is a feature: identical schemas
 * must produce identical bytes.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const schemaDir = join(root, "packages/shared-schema");
const webSrc = join(root, "packages/web/src");

const run = (cmd, args, cwd = root) =>
  execFileSync(cmd, args, { cwd, stdio: ["ignore", "inherit", "inherit"] });

const BANNER = `// GENERATED by \`pnpm gen:api\` — do not edit. Source of truth: Pydantic schemas in
// packages/api/src/tempest_api/schemas/ (CLAUDE.md §9). CI fails on drift.
`;

// 1. Pydantic → openapi.json (deterministic: sorted keys, trailing newline)
run("uv", ["run", "python", "-m", "tempest_api.dev.dump_openapi", join(schemaDir, "openapi.json")]);

// 2. openapi.json → types.ts
run("pnpm", ["--filter", "@tempest/shared-schema", "exec", "openapi-typescript", "openapi.json", "-o", "types.ts"]);

// 3. typed client
mkdirSync(join(webSrc, "lib"), { recursive: true });
writeFileSync(
  join(webSrc, "lib/api-client.ts"),
  `${BANNER}import createClient from "openapi-fetch";
import type { paths } from "@tempest/shared-schema/types";

export const apiBaseUrl =
  process.env.NEXT_PUBLIC_TEMPEST_API ?? "http://localhost:8000";

export const client = createClient<paths>({ baseUrl: apiBaseUrl });
`,
);

// 4. hooks from the spec's operations
const spec = JSON.parse(readFileSync(join(schemaDir, "openapi.json"), "utf8"));
const TS_PRIMITIVES = { integer: "number", number: "number", boolean: "boolean", string: "string" };
const hooks = [];
for (const [path, methods] of Object.entries(spec.paths ?? {}).sort()) {
  for (const [method, op] of Object.entries(methods)) {
    if (!op.operationId) {
      throw new Error(`gen:api: ${method.toUpperCase()} ${path} has no operationId — every route must set one`);
    }
    const name = op.operationId[0].toUpperCase() + op.operationId.slice(1);
    if (method === "get") {
      // Path params become hook arguments (typed from the spec) and query-key members;
      // openapi-fetch requires them in the init object, so plain-path hooks stay arg-free.
      const pathParams = (op.parameters ?? []).filter((p) => p.in === "path");
      const args = pathParams
        .map((p) => `${p.name}: ${TS_PRIMITIVES[p.schema?.type] ?? "string"}`)
        .join(", ");
      const key = [JSON.stringify(op.operationId), ...pathParams.map((p) => p.name)].join(", ");
      const init = pathParams.length
        ? `, {
        params: { path: { ${pathParams.map((p) => p.name).join(", ")} } },
      }`
        : "";
      hooks.push(`export function use${name}(${args}) {
  return useQuery({
    queryKey: [${key}],
    queryFn: async () => {
      const { data, error } = await client.GET(${JSON.stringify(path)}${init});
      if (error) throw error;
      return data;
    },
  });
}`);
    }
  }
}
mkdirSync(join(webSrc, "generated"), { recursive: true });
writeFileSync(
  join(webSrc, "generated/hooks.ts"),
  `${BANNER}import { useQuery } from "@tanstack/react-query";

import { client } from "@/lib/api-client";

${hooks.join("\n\n")}
`,
);

console.log("gen:api: openapi.json, types.ts, api-client.ts, hooks.ts regenerated");
