"""Standalone repro scripts — the product artifact. One file a developer runs to watch the
divergence themselves. Beautiful and copy-pasteable."""

from tempest.model import DivergenceClass


def render_repro_script(
    *,
    symbol: str,
    module: str,
    qualname: str,
    args_literal: str,
    kwargs_literal: str,
    divergence_class: DivergenceClass,
    base_sha: str,
    head_sha: str,
    base_summary: str,
    head_summary: str,
) -> str:
    return f'''#!/usr/bin/env python3
"""Tempest minimized reproduction — {divergence_class.value} in `{symbol}`.

  base {base_sha[:12]}: {base_summary}
  head {head_sha[:12]}: {head_summary}

Run this file from the repo root at either revision and compare what you see:

    git checkout {base_sha[:12]} && python {qualname}_repro.py
    git checkout {head_sha[:12]} && python {qualname}_repro.py

Generated by Tempest. Evidence, not opinion.
"""

import importlib
import math  # noqa: F401  (nan/inf literals below may need it on older reprs)

ARGS = {args_literal}
KWARGS = {kwargs_literal}

fn = importlib.import_module("{module}")
for part in "{qualname}".split("."):
    fn = getattr(fn, part)

print(f"calling {symbol}(*{{ARGS!r}}, **{{KWARGS!r}})")
try:
    result = fn(*ARGS, **KWARGS)
except BaseException as exc:  # observing, not handling
    print(f"raised   {{type(exc).__name__}}: {{exc}}")
else:
    print(f"returned {{result!r}}")

print()
print("tempest observed:")
print("  base {base_sha[:12]}: {base_summary}")
print("  head {head_sha[:12]}: {head_summary}")
'''
