"""Standalone repro scripts — the product artifact. One file a developer runs to watch the
divergence themselves. Beautiful, copy-pasteable, and always syntactically valid: observed
summaries are injected via repr(), never spliced raw into string literals."""

from tempest.model import DivergenceClass


def render_repro_script(
    *,
    symbol: str,
    module: str,
    qualname: str,
    args_literal: str,
    kwargs_literal: str,
    divergence_class: DivergenceClass,
    base_sha: str,
    head_sha: str,
    base_summary: str,
    head_summary: str,
    adapter_source: str | None = None,
    source_roots: tuple[str, ...] = (),
) -> str:
    safe_base = repr(base_summary)
    safe_head = repr(head_summary)
    # `[roots].source` rides inside the script (L7): run from the repo root, the configured
    # import roots are prepended so monorepo/src-layout modules resolve standalone.
    roots_prologue = (
        f"""import sys

sys.path[:0] = {list(source_roots)!r}

"""
        if source_roots
        else ""
    )
    if adapter_source is not None:
        # Synthesized-harness repro (harness/llm.py): the adapter rides INSIDE the script —
        # self-contained (L7), and the constructor call the AI chose is visible right here.
        resolve = f"""ADAPTER_SOURCE = {adapter_source!r}

# This target is an instance method, reached through the AI-written adapter below —
# executed verbatim; the constructor arguments it fixes are part of the evidence.
_ns: dict[str, object] = {{}}
exec(compile(ADAPTER_SOURCE, "tempest_adapter.py", "exec"), _ns)
fn = _ns["adapter"]
"""
    else:
        resolve = f'''import importlib

fn = importlib.import_module("{module}")
for part in "{qualname}".split("."):
    fn = getattr(fn, part)
'''
    return f'''#!/usr/bin/env python3
"""Tempest minimized reproduction — {divergence_class.value} in `{symbol}`.

Run this file from the repo root at either revision and compare what you see:

    git checkout {base_sha[:12]} && python this_file.py
    git checkout {head_sha[:12]} && python this_file.py

Generated by Tempest. Evidence, not opinion.
"""

ARGS = {args_literal}
KWARGS = {kwargs_literal}

BASE_SHA = "{base_sha[:12]}"
HEAD_SHA = "{head_sha[:12]}"
BASE_OBSERVED = {safe_base}
HEAD_OBSERVED = {safe_head}

{roots_prologue}{resolve}
print(f"calling {symbol}(*{{ARGS!r}}, **{{KWARGS!r}})")
try:
    result = fn(*ARGS, **KWARGS)
except BaseException as exc:  # observing, not handling
    print(f"raised   {{type(exc).__name__}}: {{exc}}")
else:
    print(f"returned {{result!r}}")

print()
print("tempest observed:")
print(f"  base {{BASE_SHA}}: {{BASE_OBSERVED}}")
print(f"  head {{HEAD_SHA}}: {{HEAD_OBSERVED}}")
'''
