"""Standalone repro scripts — the product artifact. One file a developer runs to watch the
divergence themselves. Beautiful, copy-pasteable, and always syntactically valid: observed
summaries are injected via repr(), never spliced raw into string literals."""

from tempest.model import DivergenceClass


def render_repro_script(
    *,
    symbol: str,
    module: str,
    qualname: str,
    args_literal: str,
    kwargs_literal: str,
    divergence_class: DivergenceClass,
    base_sha: str,
    head_sha: str,
    base_summary: str,
    head_summary: str,
) -> str:
    safe_base = repr(base_summary)
    safe_head = repr(head_summary)
    return f'''#!/usr/bin/env python3
"""Tempest minimized reproduction — {divergence_class.value} in `{symbol}`.

Run this file from the repo root at either revision and compare what you see:

    git checkout {base_sha[:12]} && python this_file.py
    git checkout {head_sha[:12]} && python this_file.py

Generated by Tempest. Evidence, not opinion.
"""

import importlib

ARGS = {args_literal}
KWARGS = {kwargs_literal}

BASE_SHA = "{base_sha[:12]}"
HEAD_SHA = "{head_sha[:12]}"
BASE_OBSERVED = {safe_base}
HEAD_OBSERVED = {safe_head}

fn = importlib.import_module("{module}")
for part in "{qualname}".split("."):
    fn = getattr(fn, part)

print(f"calling {symbol}(*{{ARGS!r}}, **{{KWARGS!r}})")
try:
    result = fn(*ARGS, **KWARGS)
except BaseException as exc:  # observing, not handling
    print(f"raised   {{type(exc).__name__}}: {{exc}}")
else:
    print(f"returned {{result!r}}")

print()
print("tempest observed:")
print(f"  base {{BASE_SHA}}: {{BASE_OBSERVED}}")
print(f"  head {{HEAD_SHA}}: {{HEAD_OBSERVED}}")
'''
