// GENERATED by `pnpm gen:api` — do not edit. Source of truth: Pydantic schemas in
// packages/api/src/tempest_api/schemas/ (CLAUDE.md §9). CI fails on drift.
import createClient from "openapi-fetch";
import type { paths } from "@tempest/shared-schema/types";

export const apiBaseUrl =
  process.env.NEXT_PUBLIC_TEMPEST_API ?? "http://localhost:8000";

export const client = createClient<paths>({ baseUrl: apiBaseUrl });
