/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/bundles/presence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Bundle Presence
         * @description Which of these content digests this server can actually SERVE — the delta-only
         *     primitive. Present means a committed run row AND the blob on disk (review M4: a crash
         *     between blob write and commit must not make peers skip the bundle forever; a lost blob
         *     must invite a re-push so the import path can heal it).
         */
        post: operations["checkBundlePresence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/divergences/{divergence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Divergence */
        get: operations["getDivergence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/divergences/{divergence_id}/repro.py": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Divergence Repro
         * @description The standalone reproduction script, byte-for-byte as the bundle carried it.
         */
        get: operations["getDivergenceRepro"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/local/prove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Local Prove
         * @description Validate repo + refs (400 REPO_NOT_FOUND / REF_NOT_FOUND), create the run, start the
         *     prove thread, and answer 202 — the UI polls `getRun` and `listRunEvents` from here.
         */
        post: operations["startLocalProve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Logs
         * @description Recent engine/sidecar log records, newest last; `level` is a minimum severity.
         */
        get: operations["listLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Newest-first run listing. Each run appears exactly once across a cursor walk.
         */
        get: operations["listRuns"];
        put?: never;
        /**
         * Create Run
         * @description Create a pending run; the CLI uploads its bundle to it afterwards. Returns 202.
         */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Run Bundle
         * @description Import a portable `.tempest.zip` produced elsewhere: repo + run are created from the
         *     manifest, then the bundle takes the exact upload ingestion path. Idempotent by content —
         *     re-importing the same bytes returns the run that already holds them.
         */
        post: operations["importRunBundle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Run Bundle
         * @description Hand back the run's `.tempest.zip` byte-identical to what was ingested (L7) — the
         *     portable artifact another Tempest imports with POST /v1/runs/import.
         */
        get: operations["exportRunBundle"];
        put?: never;
        /**
         * Upload Run Bundle
         * @description Ingest a CLI-produced `.tempest.zip` (multipart field `file`) into this pending run.
         *     Rejected bundles write nothing; the fan-out is one transaction.
         */
        post: operations["uploadRunBundle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description Stop the active prove for this run (L11): worker process groups are SIGKILLed before
         *     this returns and the prove thread unwinds into the CANCELLED state — no verdict claimed.
         */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Run Events
         * @description The run's lifecycle ledger, oldest first, as plain JSON — the desktop polls this beside
         *     run status. (Not SSE; a streaming endpoint arrives with the orchestration phase.)
         */
        get: operations["listRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search/divergences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Divergences
         * @description Index-backed text search across divergence details and base/head summaries.
         */
        get: operations["searchDivergences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Push
         * @description Push every local bundle the server lacks. Never raises on an unreachable server —
         *     the report says what remains queued (the store is the durable queue).
         */
        post: operations["syncPush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/targets/{target_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Target */
        get: operations["getTarget"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_importRunBundle */
        Body_importRunBundle: {
            /** File */
            file: string;
        };
        /** Body_uploadRunBundle */
        Body_uploadRunBundle: {
            /** File */
            file: string;
        };
        /** BundlePresenceRequest */
        BundlePresenceRequest: {
            /** Digests */
            digests: string[];
        };
        /** BundlePresenceResponse */
        BundlePresenceResponse: {
            /** Missing */
            missing: string[];
            /** Present */
            present: string[];
        };
        /**
         * CancelAccepted
         * @description 202 for cancelRun: children are already signalled; the run lands in CANCELLED.
         */
        CancelAccepted: {
            /** Cancelling */
            cancelling: boolean;
            /** Run Id */
            run_id: number;
        };
        /**
         * DivergenceClass
         * @description Taxonomy of observable behavior differences (master spec stage 7).
         * @enum {string}
         */
        DivergenceClass: "RETURN_VALUE" | "EXCEPTION_TYPE" | "EXCEPTION_MESSAGE" | "EFFECT_SEQUENCE" | "EFFECT_ARGUMENTS" | "CASSETTE_MISS" | "CRASH" | "HANG" | "OUTPUT_STREAM";
        /** DivergenceDetail */
        DivergenceDetail: {
            /** Ai Narrative */
            ai_narrative?: string | null;
            /** Args Literal */
            args_literal: string;
            /** Base Summary */
            base_summary: string;
            /** Detail */
            detail: string;
            divergence_class: components["schemas"]["DivergenceClass"];
            /** Head Summary */
            head_summary: string;
            /** Id */
            id: number;
            /** Kwargs Literal */
            kwargs_literal: string;
            /** Minimized Args */
            minimized_args: string;
            /** Minimized Kwargs */
            minimized_kwargs: string;
            /** Repro Filename */
            repro_filename: string;
            /** Run Id */
            run_id: number;
            severity: components["schemas"]["Severity"];
            /** Shrink Path */
            shrink_path: string[];
            /** Target Id */
            target_id: number;
        };
        /** DivergenceSummary */
        DivergenceSummary: {
            /** Detail */
            detail: string;
            divergence_class: components["schemas"]["DivergenceClass"];
            /** Id */
            id: number;
            /** Minimized Args */
            minimized_args: string;
            /** Minimized Kwargs */
            minimized_kwargs: string;
            severity: components["schemas"]["Severity"];
            /** Target Id */
            target_id: number;
        };
        /** ErrorBody */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
        };
        /**
         * ErrorCode
         * @description Stable machine-readable codes for the `{error: {code, message, details?}}` envelope.
         *     Renderers switch on these; the strings are frozen.
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "NOT_FOUND" | "IDEMPOTENCY_CONFLICT" | "RUN_NOT_PENDING" | "BUNDLE_INVALID" | "BUNDLE_SCHEMA_UNSUPPORTED" | "BUNDLE_MISMATCH" | "REPO_NOT_FOUND" | "REF_NOT_FOUND" | "RUN_NOT_ACTIVE" | "INTERNAL";
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Engine Version */
            engine_version: string;
            /** Schema Version */
            schema_version: number;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * Lang
         * @enum {string}
         */
        Lang: "PYTHON" | "TYPESCRIPT";
        /** LocalProveRequest */
        LocalProveRequest: {
            /** Base */
            base: string;
            /** Head */
            head: string;
            /**
             * Max Inputs
             * @default 300
             */
            max_inputs: number;
            /** Repo Path */
            repo_path: string;
        };
        /** LogRecordOut */
        LogRecordOut: {
            /** Component */
            component: string;
            /** Level */
            level: string;
            /** Message */
            message: string;
            /** Ts */
            ts: string;
        };
        /** Page[RunSummary] */
        Page_RunSummary_: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * ReasonCode
         * @description Machine-readable blocking reasons attached to every UNPROVEN verdict (Law L2).
         * @enum {string}
         */
        ReasonCode: "TARGET_UNREACHABLE" | "ENV_REPRODUCTION_FAILED" | "HARNESS_SYNTHESIS_FAILED" | "SYNTHESIS_DECLINED" | "UNINTERCEPTABLE_EFFECT" | "NONDETERMINISTIC_BASE" | "SANDBOX_UNAVAILABLE" | "VALUE_UNSERIALIZABLE" | "RECORD_REPLAY_UNAVAILABLE";
        /** RunCreate */
        RunCreate: {
            /** Base Sha */
            base_sha: string;
            /** Head Sha */
            head_sha: string;
            /** Repo */
            repo: string;
        };
        /** RunCreated */
        RunCreated: {
            /** Run Id */
            run_id: number;
        };
        /** RunDetail */
        RunDetail: {
            /** Base Deps */
            base_deps: string | null;
            /** Base Sha */
            base_sha: string;
            /** Budget Max Inputs */
            budget_max_inputs: number | null;
            /** Bundle Created At */
            bundle_created_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Divergence Count */
            divergence_count: number;
            /** Engine Version */
            engine_version: string | null;
            /** Head Deps */
            head_deps: string | null;
            /** Head Sha */
            head_sha: string;
            /** Id */
            id: number;
            /** Repo */
            repo: string;
            /** Sandbox Assurance */
            sandbox_assurance: string | null;
            /** Sandbox Tier */
            sandbox_tier: string | null;
            /** Schema Version */
            schema_version: number | null;
            status: components["schemas"]["RunStatus"];
            /** Target Count */
            target_count: number;
            /** Targets */
            targets: components["schemas"]["TargetSummary"][];
            verdict: components["schemas"]["Verdict"] | null;
        };
        /** RunEventOut */
        RunEventOut: {
            /** Level */
            level: string;
            /** Message */
            message: string;
            /** Stage */
            stage: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /**
         * RunStatus
         * @description Run lifecycle. PENDING (created) → COMPLETE (bundle ingested), or CANCELLED (the user
         *     stopped the prove — honest terminal state, no verdict ever claimed, L2/L11); further
         *     orchestration states are added — deliberately breaking the generated TS — when arq lands.
         * @enum {string}
         */
        RunStatus: "PENDING" | "COMPLETE" | "CANCELLED";
        /** RunSummary */
        RunSummary: {
            /** Base Sha */
            base_sha: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Divergence Count */
            divergence_count: number;
            /** Head Sha */
            head_sha: string;
            /** Id */
            id: number;
            /** Repo */
            repo: string;
            status: components["schemas"]["RunStatus"];
            /** Target Count */
            target_count: number;
            verdict: components["schemas"]["Verdict"] | null;
        };
        /** SearchHit */
        SearchHit: {
            divergence_class: components["schemas"]["DivergenceClass"];
            /** Divergence Id */
            divergence_id: number;
            /** Module */
            module: string;
            /** Qualname */
            qualname: string;
            /** Run Id */
            run_id: number;
            severity: components["schemas"]["Severity"];
            /** Snippet */
            snippet: string;
            /** Target Id */
            target_id: number;
        };
        /** SearchResults */
        SearchResults: {
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
            /** Query */
            query: string;
        };
        /**
         * Severity
         * @description Reporting severity: -0.0 vs 0.0 is LOW; a head-only crash is HEADLINE.
         * @enum {string}
         */
        Severity: "LOW" | "NORMAL" | "HEADLINE";
        /** SyncPushRequest */
        SyncPushRequest: {
            /** Server Url */
            server_url: string;
        };
        /** SyncReport */
        SyncReport: {
            /** Candidates */
            candidates: number;
            /** Errors */
            errors: string[];
            /** Failed */
            failed: number;
            /** Pushed */
            pushed: number;
            /** Remaining */
            remaining: number;
            /** Skipped */
            skipped: number;
        };
        /**
         * TargetClassification
         * @description Stage-1 classification of a changed symbol.
         * @enum {string}
         */
        TargetClassification: "PURE_CANDIDATE" | "IMPURE_RECORDABLE" | "UNREACHABLE" | "SYNTHESIZED" | "TYPE_SYNTHESIZED";
        /** TargetDetail */
        TargetDetail: {
            /** Changed Line Coverage */
            changed_line_coverage: number;
            classification: components["schemas"]["TargetClassification"];
            /** Divergence Count */
            divergence_count: number;
            /** Divergences */
            divergences: components["schemas"]["DivergenceSummary"][];
            /** Equivalent Inputs */
            equivalent_inputs: number;
            /** File Path */
            file_path: string;
            /** Id */
            id: number;
            /** Inputs Run */
            inputs_run: number;
            lang: components["schemas"]["Lang"];
            /** Module */
            module: string;
            /** Qualname */
            qualname: string;
            reason_code: components["schemas"]["ReasonCode"] | null;
            /** Reason Detail */
            reason_detail: string | null;
            /** Run Id */
            run_id: number;
            /** Unprovable Inputs */
            unprovable_inputs: number;
            verdict: components["schemas"]["Verdict"];
        };
        /** TargetSummary */
        TargetSummary: {
            /** Changed Line Coverage */
            changed_line_coverage: number;
            classification: components["schemas"]["TargetClassification"];
            /** Divergence Count */
            divergence_count: number;
            /** File Path */
            file_path: string;
            /** Id */
            id: number;
            lang: components["schemas"]["Lang"];
            /** Module */
            module: string;
            /** Qualname */
            qualname: string;
            reason_code: components["schemas"]["ReasonCode"] | null;
            /** Run Id */
            run_id: number;
            verdict: components["schemas"]["Verdict"];
        };
        /**
         * Verdict
         * @description The only verdicts Tempest can emit (Law L2).
         * @enum {string}
         */
        Verdict: "DIVERGENT" | "EQUIVALENT_UNDER_BUDGET" | "UNPROVEN" | "ERROR";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    checkBundlePresence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BundlePresenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundlePresenceResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getDivergence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                divergence_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DivergenceDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getDivergenceRepro: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                divergence_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/x-python": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/x-python": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/x-python": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    startLocalProve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalProveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listLogs: {
        parameters: {
            query?: {
                limit?: number;
                level?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogRecordOut"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                status?: components["schemas"]["RunStatus"] | null;
                verdict?: components["schemas"]["Verdict"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RunSummary_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replaying the same key with the same body returns the original run_id. */
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    importRunBundle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_importRunBundle"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    exportRunBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    uploadRunBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_uploadRunBundle"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelAccepted"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEventOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    searchDivergences: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    syncPush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncPushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncReport"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
